_gvcinema_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("gvcinema/movie/", include(("gvcinema.movies.urls", "movie"), namespace="movie"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gvcinema/movies/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("search", Search.as_view(), name="search"),
    path("list", List.as_view(), name="list"),
    path("details/<int:mov_exid>", Details.as_view(), name="details"),
    path("besave", BackendSave.as_view(), name="backendsave")
]

gvcinema/models.py
from django.db import models

class Genre(models.Model):
    external_id    = models.IntegerField(blank=True)
    created         = models.DateTimeField(blank=True)
    created_by      = models.CharField(max_length=45, blank=True, null=True)
    name            = models.CharField(max_length=45, blank=True)
    description     = models.CharField(max_length=105, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

class Movie(models.Model):
    external_id     = models.IntegerField(blank=True)
    created         = models.DateTimeField(blank=True)
    created_by      = models.CharField(max_length=45, blank=True, null=True)
    name            = models.CharField(max_length=45, blank=True, db_index=True)
    description     = models.CharField(max_length=255, blank=True)
    imgPath         = models.CharField(max_length=105, blank=True, null=True)
    duration        = models.IntegerField(blank=True)
    genre           = models.ManyToManyField(Genre, blank=True)
    language        = models.CharField(max_length=45, blank=True)
    mpaaRating      = models.JSONField(blank=True)
    userRating      = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

gvcinema/movies/forms.py
import json
import copy
from datetime import datetime
from django import forms
from django.db import transaction
from gvcinema.models import Genre, Movie
from _gvcinema_system.utilities.numbers import generate_alphanum 

class SearchByName(forms.Form):
    name    = forms.CharField(
        widget  = forms.TextInput(
            attrs   = {
                "class"         : "form-control form-control-lg",
                "placeholder"   : "Search movies..."
            }
        )
    )

    def clean_name(self):
        name    = self.cleaned_data.get("name")

        if not name:
            raise forms.ValidationError(
                "Must not be empty"
            )
        
        return name.strip().lower()

class SaveJsonFile(forms.Form):
    json_format = forms.JSONField(
        widget  = forms.Textarea(
            attrs   = {
                "class"         : "form-control form-control-lg",
                "placeholder"   : "Enter Json here..."
            }
        )
    )
    
    def clean_json_format(self):
        json_format = self.cleaned_data.get("json_format")
        data        = json.loads(json.dumps(json_format))

        if not json_format:
            raise forms.ValidationError(
                "Must not be empty"
            )
        
        return data
    
    def save(self):
        # Data movies
        movies_json = self.cleaned_data.get("json_format")
        
        ### SAVE GENRE ###

        # Get genre
        genre_data      = [movies.get("genre") for movies in movies_json]
        genre_list      = []
        list(map(genre_list.extend, genre_data))
        genre_clean     = list(set(genre_list))
        
        # Make sure that genre does not exists in database
        genre_save      = [genre for genre in genre_clean if not Genre.objects.filter(name=genre).exists()]
        
        # Bulking save genre
        if genre_save:
            genre_bulk_save = []
            for genre in genre_save:
                genre_bulk_save.append(
                    Genre(
                        external_id = generate_alphanum(model=Genre),
                        created     = datetime.now().replace(microsecond=0),
                        created_by  = "superadmin",
                        name        = genre
                    )
                )

            Genre.objects.bulk_create(genre_bulk_save)

        ### SAVE  MOVIES ###

        # Replace genre with genre id from database
        copy_movies_json    = copy.deepcopy(movies_json)
        movie_list          = []
       
        for movies in movies_json:
            movies["genre"] = [genre.id for genre in Genre.objects.filter(name__in=movies["genre"])]
            movie_list.append(movies)

        # Delete genre from movies json
        for movies in copy_movies_json:
            del movies["genre"]
        
        # Make sure that movies does not exists in database
        movies_save = [movie for movie in movies_json if not Movie.objects.filter(name=movie.get("name")).exists()]

        # Bulking save movies
        if movies_save:
            for movie in movies_save:
                movie["external_id"]    = generate_alphanum(model=Movie)
                movie["created"]        = datetime.now().replace(microsecond=0)
                movie["created_by"]     = "superadmin"

        Movie.objects.bulk_create([Movie(**movie) for movie in movies_save])

        ### ADD GENRE ###
        
        movies_name_genre   = [
            { "name" : movie.get("name"), "genre" : movie.get("genre") }
            for movie in movie_list
        ]

        with transaction.atomic():
            for movie in movies_name_genre:
                Movie.objects.get(name  =movie.get("name")).genre.add(*movie.get("genre"))

gvcinema/movies/views.py
import json
from datetime import datetime
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import JsonResponse
from django.views.generic.base import View
from django.conf import settings
from _gvcinema_system.utilities.messages import message
# Forms
from .forms import SearchByName as FSearchByName, SaveJsonFile as FSaveJsonFile
# Models
from gvcinema.models import Movie

class Index(View):
    template_name   = "movies/pages/index.html"
    context         = {}

    def get(self, request, *args, **kwargs):
        try:
            self.context["page_title"]      = "GV Cinema - Movies"
            self.context["content_title"]   = "Movie Listings GVCinema"
            self.context["form_search"]     = FSearchByName
        except Exception as error:
            error                   = error if settings.DEBUG else "Internal server error code #IDXGT"
            self.context["error"]   = error
            self.template_name      = "public/error.html"
        finally:
            return render(
                request,
                self.template_name,
                self.context 
            )

class List(View):
    template_name   = "movies/sections/list.html"
    context         = {}

    def get(self, request, *args, **kwargs):
        try:
            self.context["section_title"]   = "Popular Movies This Month"
            # Get movies
            movies                          = Movie.objects.all().order_by("-id")

            if request.GET and "name" in request.GET:
                name                            = request.GET.get("name")
                # Get movies
                movies                          = Movie.objects.filter(name__icontains=name).order_by("-id")
                self.context["section_title"]   = f"Show { movies.count() } movies"

            self.context["media_url"]       = settings.MEDIA_URL
            self.context["movies"]          = movies
        except Exception as error:
            error                   = error if settings.DEBUG else "Internal server error code #LSGT"
            self.context["error"]   = error
            self.template_name      = "public/error.html"
        finally:
            return render(
                request,
                self.template_name,
                self.context 
            )
       
class Details(View):
    template_name   = "movies/sections/details.html"
    context         = {}

    def get(self, request, *args, **kwargs):
        try:
            # Get movie
            movie   = Movie.objects.get(
                external_id = kwargs.get("mov_exid")
            )

            self.context["media_url"]   = settings.MEDIA_URL
            self.context["movie"]       = movie
        except Exception as error:
            error                   = error if settings.DEBUG else "Internal server error code #DTXGT"
            self.context["error"]   = error
            self.template_name      = "public/error.html"
        finally:
            return render(
                request,
                self.template_name,
                self.context 
            )

class Search(View):
    template_name   = "movies/sections/formSearch.html"
    context         = {}

    def get(self, request, *args, **kwargs):
        try:
            self.context["form_search"] = FSearchByName
        except Exception as error:
            error                   = error if settings.DEBUG else "Internal server error code #DTXGT"
            self.context["error"]   = error
            self.template_name      = "public/error.html"
        finally:
            return render(
                request,
                self.template_name,
                self.context 
            )
        
    def post(self, request, *args, **kwargs):
        try:
            form_search = FSearchByName(
                request.POST or None,
                request.FILES or None
            )

            if form_search.is_valid():
                response    = message(
                    code        = 1,
                    messages    = {
                        "message"   : [f"Success at {datetime.now()}"]
                    },
                    data        = form_search.cleaned_data.get("name")
                )
            else:
                errors      = form_search.errors
                response    = message(
                    code        = 0,
                    messages    = errors
                )
        except Exception as error:
            error   = error if settings.DEBUG else "Inter server error code #SBNPT"
            response    = message(
                code        = 1,
                messages    = {
                    "message"   : error
                }
            ) 
        finally:
            return JsonResponse(
                response
            )

class BackendSave(View):
    template_name   = "movies/pages/backendSave.html"
    context         = {}

    def get(self, request, *args, **kwargs):
        self.context["form_create"]     = FSaveJsonFile
        self.context["page_title"]      = "BE Save"
        self.context["content_title"]   = "Save to Database"
        
        return render(
            request,
            self.template_name,
            self.context
        )
    
    def post(self, request, *args, **kwargs):
        form_create = FSaveJsonFile(request.POST or None)
        if form_create.is_valid():
            data        = form_create.save()
            response    = message(
                code        = 1,
                messages    = {
                    "message"   : [f"Success at {datetime.now()}"]
                }
            )
        else:
            response    = message(
                code        = 0,
                messages    = form_create.errors
            )

        return JsonResponse(
            response
        )
    

gvcinema/views.py
from django.shortcuts import render

# Create your views here.

gvcinema/templates/movies/pages/backendSave.html
{% load static %}

{% include "public/header.html" %}

<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <div class="card">
                <div class="card-header p-3">
                    <h4 class="card-title">{{ content_title }}</h4>
                </div>
        
                <div class="card-body">
                    <h5 class="mb-3">Upload JSON file</h5>
                    
                    <form id="form-upload-json-file">
                        <form class="" id="form-upload-json-file">
                            {% csrf_token %}
                    
                            <div class="row">
                                <div class="col-lg-12 col-sm-12 col-12 mb-3">
                                    <div class="">
                                        {{ form_create.json_format }}
                                    </div>
                                </div>

                                <div class="col-lg-4 col-sm-4 col-4">
                                    <button class="btn btn-lg btn-light" type="submit">Upload</button>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-12">
                                    <div id="message-form-upload-json-file" class="mb-4"></div>
                                </div> 
                            </div>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "public/footer.html" %}

<script>
    xpost(
        "form-upload-json-file",
        "{% url 'movie:backendsave' %}",
        function(response) {
            if (response.is_success) {
                console.log(response.message)
                
                // Form reset
                document.getElementById(
                    "form-upload-json-file"
                ).reset();
                
                // Message success
                message = showMessage(
                    response.message,
                    "success",
                    "#message-form-upload-json-file"
                )
            } else {
                console.log(response.message)
                
                // Message error
                message = showMessage(
                    response.message,
                    "error",
                    "#message-form-upload-json-file"
                )
            }
        }
    )
</script>

gvcinema/templates/movies/pages/index.html
{% load static %}

{% include "public/header.html" %}

<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <div class="card">
                <div class="card-header p-3">
                    <h4 class="card-title">{{ content_title }}</h4>
                </div>
        
                <div class="card-body">
                    <div id="section-search" class="mb-4"></div>
                    <div id="section-results"></div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "public/footer.html" %}

<script>
    ajx_load(
        "section-search",
        "{% url 'movie:search' %}"
    )

    ajx_load(
        "section-results",
        "{% url 'movie:list' %}"
    )
</script>